### PR TITLE
[Storage System] Support for IBM Cloud Object Storage

### PR DESCRIPTION
**Pull request by guykhazma**
This PR adds support for IBM Cloud Object Storage (IBM COS) by creating `COSLogStore` which extends the `HadoopFileSystemLogStore` and relies on IBM COS ability to handle [atomic writes using Etags](https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-upload#upload-conditional).

The support for IBM COS relies on the following properties:
1. Write on COS is all-or-nothing, whether overwrite or not.
2. List-after-write is consistent.
3. Write is atomic when using the [Stocator - Storage Connector for Apache Spark](https://github.com/CODAIT/stocator) (v1.1.1+) and setting the configuration `fs.cos.atomic.write` to `true`.

In addition I propose the following [documentation](https://docs.google.com/document/d/1ued0rajmIZPZXJZ65uvvUTb088rcsxLl3zct1Y5A4p8/edit) to be added to the [Storage Configuration](https://docs.delta.io/latest/delta-storage.html) page.

### CODE REVIEW

**Comment by databricks-cla-assistant** [comment]
[CLA assistant check](https://cla.dev.databricks.com/delta-io/delta?pullRequest=302) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.databricks.com/delta-io/delta?pullRequest=302) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dev.databricks.com/check/delta-io/delta?pullRequest=302) it.</sub>

**Comment by guykhazma** [comment]
The build fails because the license comment in the new class doesn't contain the copyright line.
Since the project was donated to Linux Foundation I wasn't sure which copyright to use.

File: src/main/scala/org/apache/spark/sql/delta/storage/COSLogStore.scala [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+import org.apache.hadoop.conf.Configuration
+import org.apache.hadoop.fs.{FileSystem, Path}
+import org.apache.spark.SparkConf
+
+/**
+ * LogStore implementation for IBM Cloud Object Storage.
+ *
+ * We assume the following from COS's [[FileSystem]] implementations:
+ * - Write on COS is all-or-nothing, whether overwrite or not.
+ * - Write is atomic.
```
Comment (zsxwing) [inline src/main/scala/org/apache/spark/sql/delta/storage/COSLogStore.scala]: LogStore also requires `Mutual exclusion: Only one writer must be able to create (or rename) a file at the final destination.`. What's the behavior when multiple writes are happening at the same time?

In addition, according to the doc `enable or disable atomic writes to COS using Etags. When the flag fs.cos.fast.upload is set true atomic writes will be available only for writes that require only one block.`, looks like atomic write doesn't work for large files?

**Comment by zsxwing** [comment]
@guykhazma Thanks a lot for your contribution. As we don't have an environment to test it, could you clarify what tests you have done in a real environment?

File: src/main/scala/org/apache/spark/sql/delta/storage/COSLogStore.scala (hunk 1 above)
Comment (guykhazma) [reply src/main/scala/org/apache/spark/sql/delta/storage/COSLogStore.scala]: The implementation of atomic write use Etags for concurrency control.
The high level flow is:
1. Take HEAD of object at path to check if it exists and if yes get Etag `e`.
- If object doesn't exist then do a PUT using header `If-None-Match: *`.
- Will only succeed if this is the first PUT to that object name.
- If this fails because of constraint (concurrent write) then throw an illegal state . 
2. If object exists and `overwrite == false` throw file already exists exception.
3. If object exists and `overwrite == true`, PUT object using header `If-Match: e`.
- If this fails because of constraint (concurrent write) then throw an illegal state exception.

So in case of multiple writers at the same time only one will succeed while the others will get an exception.
For example see this exception:
```
Exception in thread "Thread-14" java.lang.IllegalStateException: Failed due to concurrent write
        at org.apache.spark.sql.delta.storage.COSLogStore.write(COSLogStore.scala:53)
        at org.apache.spark.sql.delta.storage.LogStoreTests$$anon$1.run(LogStoreTests.scala:43)
Caused by: java.io.IOException: saving output tmp/delta_try1/_delta_log/0 com.amazonaws.services.s3.model.AmazonS3Exception: At least one of the preconditions you specified did not hold. (Service: Amazon S3; Status Code: 412; Error Code: PreconditionFailed; Request ID: 5c8dd3e6-f6b9-4a17-9d13-88ff7a274d04; S3 Extended Request ID: null), S3 Extended Request ID: null
        at com.ibm.stocator.fs.cos.COSOutputStream.close(COSOutputStream.java:197)
        at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
        at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
        at org.apache.spark.sql.delta.storage.COSLogStore.write(COSLogStore.scala:50)
        ... 1 more
```
<br>
As for large files - The use of Etags is supported currently for `PutObjectRequest` therefore it means that the atomic write support is available only when the write is done in one chunk.
The documentation wasn't clear about that so I have updated it accordingly (the documentation in the connector will be updated as well):

```
Note: Atomic write is available only when the write is done in one chunk. 
- When the flag `fs.cos.fast.upload` is set to `false` atomic write will be available only for write that is lower or equal to `fs.cos.multipart.threshold size` (by default max integer). 
- When the flag `fs.cos.fast.upload` is set to `true` atomic write will be available only for write that require only one block .
```

So we expect writes that go through the LogStore to be written in one chunk by the connector in order to achieve mutual exclusion.
Note that using the default configuration (`fs.cos.fast.upload=false`) write is done in one chunk for files of about ~2.15GB so it should be reasonable.

**Comment by guykhazma** [comment]
@zsxwing thanks for reviewing.
I have tested the LogStore implementation directly to verify it achieves the mutual exclusion requirement by running multiple writes to the same location in threads and verifying that only one succeeds.
The 2 other requirements are properties of the storage system so they should be OK as well.

File: src/main/scala/org/apache/spark/sql/delta/storage/COSLogStore.scala (hunk 1 above)
Comment (guykhazma) [reply src/main/scala/org/apache/spark/sql/delta/storage/COSLogStore.scala]: Adding to the previous comment, looking at the current code these are the places where a write is done using the LogStore API:

1. Writing the `_last_checkpoint` file - https://github.com/delta-io/delta/blob/7c2c0dabff5fb48b2e08c2b1c9ef1ffbedf11c95/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala#L122

2. Writing the actions during commit -
- https://github.com/delta-io/delta/blob/7c2c0dabff5fb48b2e08c2b1c9ef1ffbedf11c95/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala#L401
- https://github.com/delta-io/delta/blob/7c2c0dabff5fb48b2e08c2b1c9ef1ffbedf11c95/src/main/scala/org/apache/spark/sql/delta/commands/ConvertToDeltaCommand.scala#L361

3. Writing manifest file for Presto/Athena - https://github.com/delta-io/delta/blob/7c2c0dabff5fb48b2e08c2b1c9ef1ffbedf11c95/src/main/scala/org/apache/spark/sql/delta/hooks/GenerateSymlinkManifest.scala#L243

1 is a small fixed sized object, and for 2 and 3 I think it's reasonable to assume that these writes should be below the default threshold of ~2.15GB to ensure these writes are done in one chunk and so can be atomic. If needed in special cases the user can configure the threshold differently.

In addition regarding the write of the checkpoint: 
https://github.com/delta-io/delta/blob/7c2c0dabff5fb48b2e08c2b1c9ef1ffbedf11c95/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala#L228
since write in COS is not partially visible this should be OK as well.

In addition I have added checks to the LogStore implementation to make sure the write will be atomic.

**Comment by guykhazma** [comment]
Hi @zsxwing can you please review the PR.

**Comment by guykhazma** [comment]
@zsxwing gentle ping, @tdas @mukulmurthy I'll appreciate your review as well.

**Comment by guykhazma** [comment]
Hi @zsxwing, @tdas, @rahulsmahadev,
I have updated the PR to include the new copyright title and the build pass.
Can you please review this PR
Thanks!

**Comment by guykhazma** [comment]
@zsxwing, @tdas, @rahulsmahadev can you please review the PR

**Comment by zsxwing** [comment]
Sorry for the delay. We are working on adding a `contrib` directory and a new project to put all future LogStore implementations like this. We would like to keep the core project small because special LogStore implementations are not needed by everyone. Will report back when the project is ready.

File: src/main/scala/org/apache/spark/sql/delta/storage/COSLogStore.scala (hunk 1 above)
Comment (guykhazma) [reply src/main/scala/org/apache/spark/sql/delta/storage/COSLogStore.scala:32]: IBM COS supports now conditional headers on multipart uploads as well so this is no longer necessary.
The PR and proposed doc was updated to remove these checks.

**Comment by guykhazma** [comment]
Hi @zsxwing, @tdas, @rahulsmahadev,
IBM COS supports now conditional headers on multipart upload requests as well (see [here](https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-upload#upload-conditional)) so I have updated the PR to remove the checks that made sure the write is not using multipart upload.

Now that version 0.7.0 was released can you please take a look and see if this can get in.
Thanks

**Comment by robbyki** [comment]
Any timeline on when this might get into master?

**Comment by tdas** [comment]
Hey @guykhazma 

Our apologies for sitting on the PR for so long. We wanted to figure out what is the best we integrate slightly less battle-tested features into our repo, and we finally figured it out. We are currently in the process of converting our repo to a multi-module SBT project so that we can add other sub-modules (mapping to other maven release artifacts beyond delta-core). Then we can add a `contribs` module and then accept such new and experimental features.

Are you still interested in contributing to this feature?

**Comment by guykhazma** [comment]
Hi @tdas ,

Thanks for getting back to me.
Yes I would love for this to get in. I think it will be great to enable Delta Lake using IBM Cloud Object Storage.
Let me know when it's ready and I'll do the necessary refactor to the PR.

**Comment by tdas** [comment]
Awsome! thank you! I will ping you when this refactor is merged.

**Comment by tdas** [comment]
All right! The multi-module refactor has been merged. Let's discuss the next steps forward to get this ready for merging. 

1. Please define a new module using the same pattern as the `core` module in the build.sbt file.
    - Does the IBM support need additional maven dependencies? I am guessing not. In that case, we can make the module name generic like "delta-contribs" (that is, not specific to IBM). Other such zero-dependency contributions can go in that project as well. Otherwise, lets put it in a specifically named module like "delta-contribs-ibm"
   
2. Move the new log store code inside the `<new-module-dir>/src/main/<package>/...` and the test code in a separate file in `<new-module-dir>/src/test/<package>/...`.

Let me know if you need help to get it working.

**Comment by guykhazma** [comment]
Thanks for the update @tdas.
I will update the PR and will tag you when it's ready.

**Comment by guykhazma** [comment]
@tdas I have made the changes but didn't change the documentation yet.
I guess we want to add to the README the new model so I can suggest something but was not sure if you already something in mind.

**Comment by guykhazma** [comment]
Hi @tdas ,

Any updates?

Thanks!

**Comment by tdas** [comment]
My apologies for the delay, we have been trying to line up a few more features like a new, more stable [LogStore API](https://github.com/delta-io/delta/commit/b7cb203dd23a9a225fbcc414bc075916bd32a817) that LogStore builders like you folks can use. However, there are a few more pieces that we still need to get in for the public API to be easily usable. I dont want you folks to block on those. So we can continue working using the existing LogStore API, which we will continue supporting for at least the 1.x releases. Later we can rewrite the IBMLogStore to use the new API, we are not going to worry about the 1.0 release we are targeting in a couple of weeks.

Let me leave some quick comments

File: build.sbt [hunk 2]
```diff
@@ -95,6 +95,70 @@ lazy val core = (project in file("core"))
...
   )
 
+lazy val deltacontribs = (project in file("delta-contribs"))
+  .enablePlugins(GenJavadocPlugin, JavaUnidocPlugin, ScalaUnidocPlugin)
+  .dependsOn(core)
+  .settings (
+    name := "delta-contribs",
+    commonSettings,
+    scalaStyleSettings,
+    unidocSettings,
```
Comment (tdas) [inline build.sbt:105]: i dont think we need unidoc

File: build.sbt [hunk 3]
```diff
@@ -95,6 +95,70 @@ lazy val core = (project in file("core"))
...
+    releaseSettings,
+    libraryDependencies ++= Seq(
```
Comment (tdas) [inline build.sbt:107]: do we need to add these dependencies? I think this project automatically gets the dependencies from the core module

File: build.sbt [hunk 4]
```diff
@@ -95,6 +95,70 @@ lazy val core = (project in file("core"))
...
+      "junit" % "junit" % "4.12" % "test",
+      "com.novocode" % "junit-interface" % "0.11" % "test",
+      "org.apache.spark" %% "spark-catalyst" % sparkVersion % "test" classifier "tests",
+      "org.apache.spark" %% "spark-core" % sparkVersion % "test" classifier "tests",
+      "org.apache.spark" %% "spark-sql" % sparkVersion % "test" classifier "tests",
+      "org.apache.spark" %% "spark-hive" % sparkVersion % "test" classifier "tests",
+
+      // Compiler plugins
+      // -- Bump up the genjavadoc version explicitly to 0.16 to work with Scala 2.12
+      compilerPlugin("com.typesafe.genjavadoc" %% "genjavadoc-plugin" % "0.16" cross CrossVersion.full)
```
Comment (tdas) [inline build.sbt:125]: if you remove unidoc settings, then we probably dont need this.

File: build.sbt [hunk 5]
```diff
@@ -95,6 +95,70 @@ lazy val core = (project in file("core"))
     (compile in Compile) := ((compile in Compile) dependsOn createTargetClassesDir).value
   )
 
+lazy val deltacontribs = (project in file("delta-contribs"))
+  .enablePlugins(GenJavadocPlugin, JavaUnidocPlugin, ScalaUnidocPlugin)
+  .dependsOn(core)
```
Comment (tdas) [inline build.sbt:100]: I think your tests are failing because the tests of this module is not depending on the tests of the core module. Hence the tests are showing this following compilation error
```
[info] Resolving org.antlr#antlr-master;3.5.2 ...
[error] /home/circleci/project/delta-contribs/src/test/scala/org/apache/spark/sql/delta/LogStoreSuite.scala:21: not found: type LogStoreSuiteBase
[error] class COSLogStoreSuite extends LogStoreSuiteBase {
[error]                                ^
[error] /home/circleci/project/delta-contribs/src/test/scala/org/apache/spark/sql/delta/LogStoreSuite.scala:24: value sparkConf is not a member of AnyRef
[error]     super.sparkConf.set(logStoreClassConfKey, logStoreClassName)
[error]           ^
[error] /home/circleci/project/delta-contribs/src/test/scala/org/apache/spark/sql/delta/LogStoreSuite.scala:24: not found: value logStoreClassConfKey
[error]     super.sparkConf.set(logStoreClassConfKey, logStoreClassName)
[error]                         ^
[info] Resolving org.sonatype.oss#oss-parent;9 ...

[info] Resolving org.antlr#ST4;4.0.8 ...

[info] Resolving org.antlr#ST4;4.0.8 ...
[error] /home/circleci/project/delta-contribs/src/test/scala/org/apache/spark/sql/delta/LogStoreSuite.scala:30: not found: value testHadoopConf
[error]   testHadoopConf(
[error]   ^
[error] /home/circleci/project/delta-contribs/src/test/scala/org/apache/spark/sql/delta/LogStoreSuite.scala:31: not found: value expectedErrMsg
[error]     expectedErrMsg = ".*No FileSystem for scheme.*fake.*",
[error]     ^
[info] Resolving org.sonatype.oss#oss-parent;9 ...

[info] Resolving org.abego.treelayout#org.abego.treelayout.core;1.0.3 ...

[info] Resolving org.abego.treelayout#org.abego.treelayout.core;1.0.3 ...

[info] Resolving org.sonatype.oss#oss-parent;7 ...

[info] Resolving org.sonatype.oss#oss-parent;7 ...
[error] /home/circleci/project/delta-contribs/src/test/scala/org/apache/spark/sql/delta/LogStoreSuite.scala:32: not found: type FakeFileSystem
[error]     "fs.fake.impl" -> classOf[FakeFileSystem].getName,
[error]                               ^
[error] 6 errors found
```

The fix probably is 
```
.dependsOn(core % "compile->compile;test->test")
```

File: build.sbt (hunk 3 above)
Comment (guykhazma) [reply build.sbt:105]: I have removed almost all of the dependencies but `spark-sql` which is needed.
Because the `spark-sql` dependency is `provided` in the `core` module it is not resolved as a transitive dependency for the `delta-contrib` module.
(If we'll make the `spark-sql` module a `compile` dependency in the core then it works fine but I didn't want to change the `core` module dependencies)

**Comment by guykhazma** [comment]
@tdas thanks for the update and review. I made the needed changes please note the comment about the library dependencies and let me know what you think.

Also, let me know when you want to have the change to use the new API and I'll open a PR for that.

Thanks

File: build.sbt (hunk 3 above)
Comment (guykhazma) [reply build.sbt]: adding `provided->provided` solved it.

File: delta-contribs/src/main/scala/org/apache/spark/sql/delta/storage/COSLogStore.scala [hunk 6]
```diff
@@ -0,0 +1,87 @@
...
+ *
+ * We assume the following from COS's [[FileSystem]] implementations:
+ * - Write on COS is all-or-nothing, whether overwrite or not.
+ * - Write is atomic.
+ *   Note: Write is atomic when using the Stocator v1.1.1+ - Storage Connector for Apache Spark
+ *   (https://github.com/CODAIT/stocator) by setting the configuration `fs.cos.atomic.write` to true
+ *   (for more info see the documentation for Stocator)
+ * - List-after-write is consistent.
+ */
+class COSLogStore(sparkConf: SparkConf, hadoopConf: Configuration)
```
Comment (tdas) [inline delta-contribs/src/main/scala/org/apache/spark/sql/delta/storage/COSLogStore.scala:39]: Is COSLogStore the best name for this? Typically we are moving towards the putting the cloud name in the logStore (like AzureLogStore) because 
(i) usually the cloud name is more easily recognizable than the specific storage system name. 
(ii) usually a cloud has a single scalable storage solution and there fore one log store implementation is sufficient for the cloud (Azure has multiple storage solutions but they have same semantics so luckily one logstore implementation was good enough)

So in this case, wouldn't it be more recognizable in general if we put IBM in the name. like "IBMLogStore" or "IBMCOSLogStore"?

**Comment by tdas** [comment]
@guykhazma thank you for the speedy response. regarding the new LogStore APIs, I think we have to first convert the HadoopLogStore base class to use the new APIs, only then can the subclasses extending HadoopLogStore also use the new APIs easily. 

It can be done after this PR. If you are interested, you can take a crack at it if you want!

File: build.sbt [hunk 7]
```diff
@@ -95,6 +95,47 @@ lazy val core = (project in file("core"))
     (compile in Compile) := ((compile in Compile) dependsOn createTargetClassesDir).value
   )
 
+lazy val deltacontribs = (project in file("delta-contribs"))
```
Comment (tdas) [inline build.sbt:98]: name the val as "contribs" similar to "core"

File: delta-contribs/src/test/scala/org/apache/spark/sql/delta/LogStoreSuite.scala [hunk 8]
```diff
@@ -0,0 +1,36 @@
...
+  }
+
+  override val logStoreClassName: String = classOf[COSLogStore].getName
+
+  testHadoopConf(
+    expectedErrMsg = ".*No FileSystem for scheme.*fake.*",
+    "fs.fake.impl" -> classOf[FakeFileSystem].getName,
+    "fs.fake.impl.disable.cache" -> "true")
+
+  protected def shouldUseRenameToWriteCheckpoint: Boolean = false
```
Comment (tdas) [inline delta-contribs/src/test/scala/org/apache/spark/sql/delta/LogStoreSuite.scala:35]: this is not really testing on actual IBM cloud ... do you folks have full integration testing on your side to really test the atomic guarantees etc.?

File: delta-contribs/src/main/scala/org/apache/spark/sql/delta/storage/COSLogStore.scala [hunk 9]
```diff
@@ -0,0 +1,87 @@
...
+  extends HadoopFileSystemLogStore(sparkConf, hadoopConf) {
+  val preconditionFailedExceptionMessage =
+    "At least one of the preconditions you specified did not hold"
+
+  assert(hadoopConf.getBoolean("fs.cos.atomic.write", false) == true,
```
Comment (tdas) [inline delta-contribs/src/main/scala/org/apache/spark/sql/delta/storage/COSLogStore.scala:44]: shouldnt we throw a better error message than a simple assertion ... explaining what failed and how to fix it? Otherwise, how would the user understand a message saying "AssertionError: false not equal to true"?

Comment (guykhazma) [reply delta-contribs/src/main/scala/org/apache/spark/sql/delta/storage/COSLogStore.scala]: There was an explanation below this line. I enhanced it a bit.

File: delta-contribs/src/test/scala/org/apache/spark/sql/delta/LogStoreSuite.scala [hunk 10]
```diff
@@ -0,0 +1,36 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.apache.spark.sql.delta
+
+import org.apache.spark.sql.delta.storage._
+
+class IBMCOSLogStoreSuite extends LogStoreSuiteBase {
```
Comment (tdas) [inline delta-contribs/src/test/scala/org/apache/spark/sql/delta/LogStoreSuite.scala:21]: please make the file name match the class name. there maybe other logstores and logstore suites in the contrib module.

File: delta-contribs/src/main/scala/org/apache/spark/sql/delta/storage/COSLogStore.scala (hunk 9 above)
Comment (tdas) [reply delta-contribs/src/main/scala/org/apache/spark/sql/delta/storage/COSLogStore.scala]: thank you!

File: delta-contribs/src/test/scala/org/apache/spark/sql/delta/LogStoreSuite.scala (hunk 8 above)
Comment (tdas) [reply delta-contribs/src/test/scala/org/apache/spark/sql/delta/LogStoreSuite.scala]: yeah. i dont have a good way. even our existing AzureLogStore and S3SingleDriverLogStore do not have cloud-specific unit tests for the same reasons... the complexity of maintaining it in a public repo. As long you folks have integration tests, that's good enough for now.

**Comment by guykhazma** [comment]
@tdas thanks for the review!
I can try and help with converting the HadoopLogStore base class to use the new APIs sometime in the coming weeks.

**Comment by tdas** [comment]
awesome. this looks good now. i will start the process of merging this! thank you for the super quick response!

**Comment by tdas** [comment]
@guykhazma question for you! what is the git email address that you want to use for the commits? Linux foundation guideline requires having an email address tied to each contribution. and your github profile does not have any email on it.

**Comment by guykhazma** [comment]
@tdas please use guykhag@gmail.com. thanks!

**Comment by guykhazma** [comment]
@tdas , I thought you needed an email not tied to an organization, then you can use Guy.Khazma@ibm.com as well.
