### PR TITLE
Add DELTA_TESTING=1 environment variable when running Python tests

### PR DESCRIPTION
**Pull request by zhipengmao-db**
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [x] Other (fill in here)

## Description

In Python tests, we want to test features that are only for testing. But `DELTA_TESTING=1` is missing for Python tests. So this PR adds it to the environment variable when running Python tests.

## How was this patch tested?

Not applicable.

## Does this PR introduce _any_ user-facing changes?

No.

### CODE REVIEW

**Review by c27kwan — APPROVED** [review]
lgtm! Thanks for fixing this :)

**Review by vkorukanti — APPROVED** [review]

**Comment by tdas** [comment]
6 tests have failed in master. are they related? if so, can you fix them?

**Comment by vkorukanti** [comment]
> 6 tests have failed in master. are they related? if so, can you fix them?

test failures are fixed in https://github.com/delta-io/delta/pull/3442

**Comment by zhipengmao-db** [comment]
The error in spark master test is not related to the change as it fails in other PRs as well.
```
[error] /home/runner/work/delta/delta/spark-connect/server/src/test/scala-spark-master/io/delta/connect/DeltaConnectPlannerSuite.scala:60:58: value forTesting is not a member of object org.apache.spark.sql.connect.service.SessionHolder
[error]       val result = new SparkConnectPlanner(SessionHolder.forTesting(spark)).transformRelation(input)
[error]                                                          ^
[error] /home/runner/work/delta/delta/spark-connect/server/src/test/scala-spark-master/io/delta/connect/DeltaConnectPlannerSuite.scala:86:58: value forTesting is not a member of object org.apache.spark.sql.connect.service.SessionHolder
[error]       val result = new SparkConnectPlanner(SessionHolder.forTesting(spark)).transformRelation(input)
[error]                                                          ^
[warn] /home/runner/work/delta/delta/spark-connect/server/src/test/scala-spark-master/io/delta/connect/DeltaConnectPlannerSuite.scala:27:68: Unused import
[warn] import org.apache.spark.sql.connect.delta.ImplicitProtoConversions._
[warn]                   
```
