### PR TITLE
[Spark] Fix NoClassDefFoundError on Spark 4.1.2 -- IgnoreCachedData

### PR DESCRIPTION
**Pull request by timothyw553**
#### Which Delta project/connector is this regarding?

- [x] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

## Description

`delta-spark_4.1` is built against Spark 4.1.0. Spark 4.1.2 backported [SPARK-54812](https://github.com/apache/spark/pull/53572), which removed the `IgnoreCachedData` trait. Our `spark-4.1` shim still does `extends IgnoreCachedData`, so the missing trait is baked into the jar. On Spark 4.1.2, loading any Delta command that uses this shim (`ALTER TABLE`, `TRUNCATE`, `REORG`/`OPTIMIZE`) fails with `NoClassDefFoundError`.

We need this fix because users cannot run these commands on Spark 4.1.2 today.

This PR builds the 4.1 line against the latest patch (4.1.2) and turns the `spark-4.1` shim into an empty marker, like the existing `spark-4.2` shim. 4.1.2 changed only this one API that Delta shims (confirmed by looking at all the changes between 4.1.1 and 4.1.2 with the help of Claude), and all of these commands extend `Command`, which the new `CacheManager` skips on its own. The artifact name stays `delta-spark_4.1`, and CI now builds against 4.1.2.

Also needed to temporarily bump up `UV_EXCLUDE_NEWER` because PySpark 4.1.2 is released after the existing `UV_EXCLUDE_NEWER`

## How was this patch tested?

Compiled against Spark 4.1.2:
- `build/sbt -DsparkVersion=4.1.2 "sparkV1 / Compile / compile"` -> success
- `build/sbt -DsparkVersion=4.1.2 "spark / Compile / compile"` -> success
- `python3 project/scripts/get_spark_version_info.py --get-field 4.1 fullVersion` -> `4.1.2`

The Spark 4.1 CI matrix now runs on 4.1.2.

## Does this PR introduce _any_ user-facing changes?
Yes. The Spark 4.1 build now targets Spark 4.1.2. `ALTER TABLE`, `TRUNCATE`, and `REORG` on Delta tables work again on Spark 4.1.2, where they failed before with `NoClassDefFoundError`.

### CODE REVIEW

File: .github/workflows/spark_python_test.yaml [hunk 1]
```diff
@@ -92,8 +92,12 @@ jobs:
           else
             uv pip install --python .venv/bin/python --require-hashes -r .github/ci-requirements/spark-python/spark4.1.lock
           fi
-          # pyspark installed with --no-deps: its only transitive dep (py4j) is in the lock file
-          uv pip install --python .venv/bin/python --no-deps pyspark==${{ steps.spark-details.outputs.spark_full_version }}
+          # pyspark is installed with --no-deps: its only transitive dep (py4j) is in the lock file.
+          # Spark 4.1.2 was published after the global package cutoff, so relax the cutoff only
+          # for this single no-deps install.
+          UV_EXCLUDE_NEWER=2026-05-22T00:00:00Z \
```
Comment (timothyw553) [inline .github/workflows/spark_python_test.yaml:98]: or is it safe to bump the global one?

File: project/CrossSparkVersions.scala [hunk 2]
```diff
@@ -276,7 +276,7 @@ object SparkVersionSpec {
   )
 
   private val spark41 = SparkVersionSpec(
-    fullVersion = "4.1.0",
+    fullVersion = "4.1.2",
```
Comment (seewishnew) [inline project/CrossSparkVersions.scala:279]: We need to ensure that this still continues to work with Spark-4.1.0.

Comment (seewishnew) [reply project/CrossSparkVersions.scala:279]: Doing this might just side-step 4.1.0 compatibility issue. It looks like Spark-4.1.0 and 4.1.2 are fundamentally incompatible

File: spark/src/main/scala-shims/spark-4.1/IgnoreCachedDataShim.scala [hunk 3]
```diff
@@ -16,10 +16,11 @@
...
- * shim is an empty marker.
+ * Shim for Spark's `IgnoreCachedData` trait. SPARK-54812 removed the trait and changed
+ * `CacheManager` to automatically skip any `Command`-derived plan during cache replacement.
+ * That change shipped in Spark 4.2 and was backported to Spark 4.1.2, so the 4.1 line now
+ * targets 4.1.2 (see CrossSparkVersions) and this is an empty marker, same as the 4.2 variant.
+ * All Delta commands that mix this in already extend `RunnableCommand`/`Command`, so they are
+ * covered by the new automatic path.
  */
-trait IgnoreCachedDataShim extends IgnoreCachedData
+trait IgnoreCachedDataShim
```
Comment (seewishnew) [inline spark/src/main/scala-shims/spark-4.1/IgnoreCachedDataShim.scala:26]: I think this will break with Spark-4.1.0 because there's no fallback to Spark-4.1.0's IgnoreCachedData.

File: project/CrossSparkVersions.scala (hunk 2 above)
Comment (seewishnew) [reply project/CrossSparkVersions.scala:279]: To do this while ensuring full backwards compatibility, we may need to repeat Spark-4.2's build steps for 4.1.2; not override spark-4.1's steps.

**Comment by felipepessoto** [comment]
Is this duplicate? #6913

**Comment by timothyw553** [comment]
@felipepessoto ah yes, thanks for pointing that out!
