### PR TITLE
[Spark] Move changelog tests to spark-unified to fix Spark 4.2 classpath

### PR DESCRIPTION
**Pull request by SanJSp**
#### Which Delta project/connector is this regarding?

- [x] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

## Description

Move the changelog tests to `spark-unified/test` as we had a circular dependency in the tests from sparkV2 to spark-unified and from spark-unified to sparkV2. Fixes the `ClassCastException` at `AbstractDeltaCatalog.scala:1118`.

## How was this patch tested?

See "How I build" at the bottom for the full command. Ran `DeltaChangelogTestBase.java`. Result on Spark 4.2-preview4:

```
[info] Passed: Total 21, Failed 0, Errors 0, Passed 21
[success] Total time: 76 s
```

Furthermore ran my tests in private repo CI https://github.com/SanJSp/delta/actions/runs/26287328831/job/77378150469?pr=2

## Does this PR introduce _any_ user-facing changes?

No. The two small Java edits in `DeltaChangelogScanBuilder.java` and `DeltaChangelogBatch.java` affect the V2 changelog code path's error-reporting (which error class surfaces to the user when row tracking is misconfigured), but the V2 changelog path remains gated behind `delta.changelogV2.enabled` and is not used in any released code path today.

<details><summary>How I build</summary>

## Quick reference: minimal cherry-pick to build + test against Spark 4.2

Verified: **21 / 21 changelog tests pass** with this setup. Without PR #6657, compile fails on Spark 4.2 ABI shifts. Without this PR (#6830), tests fail at the first `spark.sql(...)` call with `ClassCastException` from `SupportsPathIdentifier`, followed by `NoSuchMethodError: CatalogStorageFormat.copy(6 args)` once that cast is fixed.

```bash
# Start from upstream master
git fetch delta_oss_upstream
git checkout -b test-changelog-spark42 delta_oss_upstream/master

# Pull PR #6657 (Spark 4.2 ABI shims, 25+ commits from Murali + Vishnu)
git fetch delta_oss_upstream pull/6657/head:pr-6657
git merge --no-ff --no-edit pr-6657

# Pull PR #6830 (this PR — changelog test classpath + 3 fixes + CI scoping)
git fetch delta_oss_upstream pull/6830/head:pr-6830
git merge --no-ff --no-edit pr-6830

# Local-only edits in project/CrossSparkVersions.scala (do NOT commit; the
# maven proxy does not mirror Apache snapshots, so the SNAPSHOT pin from
# PR #6657 has to be swapped for a released preview):
sed -i 's|fullVersion = "4.2.0-SNAPSHOT"|fullVersion = "4.2.0-preview4"|' \
  project/CrossSparkVersions.scala
sed -i 's|val MASTER: Option\[SparkVersionSpec\] = None|val MASTER: Option[SparkVersionSpec] = Some(spark42Snapshot)|' \
  project/CrossSparkVersions.scala
sed -i 's|val ALL_SPECS = Seq(spark40, spark41)$|val ALL_SPECS = Seq(spark40, spark41, spark42Snapshot)|' \
  project/CrossSparkVersions.scala

# Build + test
JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 \
PATH=/usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH \
MAVEN_PROXY_URL=https://maven-proxy.dev.REDACTED.com \
MAVEN_MIRROR_URL=https://maven-proxy.dev.REDACTED.com \
DEFAULT_ARTIFACT_REPOSITORY=https://maven-proxy.dev.REDACTED.com \
./build/sbt -DsparkVersion=master \
  "set every scalastyleFailOnError := false" \
  "spark/testOnly io.delta.spark.internal.v2.read.changelog.*"
```

Expected:

```
[info] Passed: Total 21, Failed 0, Errors 0, Passed 21
[success] Total time: ~80 s
```

The `DeltaChangelogTestBase.java` conflict from the PR #6657 merge has to be resolved with `git rm` (PR #6830 deletes the file from `sparkV2/test`, PR #6657 modifies it):

```bash
# If the merge of pr-6830 reports a CONFLICT (modify/delete) on DeltaChangelogTestBase.java:
git rm spark/v2/src/test/scala-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogTestBase.java
git commit --no-edit
```

---

</details>

### CODE REVIEW

File: build.sbt [hunk 1]
```diff
@@ -561,6 +561,20 @@ lazy val spark = (project in file("spark-unified"))
 
     CrossSparkVersions.sparkDependentSettings(sparkVersion),
 
+    // Mirror what `sparkDependentSettings` does for the version-specific test shim directory,
+    // but root it at this module's baseDirectory instead of `Test / baseDirectory` (which points
+    // at sparkV1). Without this, version-gated tests that live under spark-unified (e.g. the
+    // changelog tests under `scala-shims/spark-4.2`) are never compiled, and tests that exist
+    // only for Spark 4.2 would also be compiled against 4.0/4.1 if the path were unconditional.
```
Comment (johanl-db) [inline build.sbt]: nit: more simply:

Add version-specific test shim directory, e.g. `src/test/scala-shims/spark-4.2`

File: spark-unified/src/test/scala-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogTestBase.java [hunk 2]
```diff
@@ -0,0 +1,130 @@
...
+ * carries a pre-#5320 {@code DeltaCatalog.class} (no {@code AbstractDeltaCatalog} ancestor) which
+ * shadows the in-tree class at the same FQN and produces a runtime {@code ClassCastException} from
+ * {@code SupportsPathIdentifier}'s self-type cast. {@code spark-unified} does not depend on {@code
+ * sparkV2} at {@code test->test}, so the released jar is not on its test classpath.
+ *
+ * <p>This class is intentionally self-contained (does not extend {@code DeltaV2TestBase}) because
+ * {@code DeltaV2TestBase} lives in {@code sparkV2}'s test scope and is not visible from {@code
+ * spark-unified}.
+ */
+public abstract class DeltaChangelogTestBase {
```
Comment (johanl-db) [inline spark-unified/src/test/scala-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogTestBase.java]: I assume spark-unified test target doesn't depend on sparkV2 test target so that you can't use `DeltaV2TestBase` here?

Might be helpful to be able to reuse things from sparkV2 tests though. Not super important here, but if it's easily doable to have this dependency it would be worth doing rather than redefining every helper

**Review by johanl-db — COMMENTED** [review]
The PR description is really verbose, trim it down so that it's easy to grasp the essential information

File: spark-unified/src/test/scala-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogTestBase.java (hunk 2 above)
Comment (SanJSp) [reply spark-unified/src/test/scala-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogTestBase.java]: Done — added ExclusionRule("io.delta", "delta-spark_2.13") to excludeDependencies to drop the released delta-spark from spark-unified's test classpath (totherwise would re-introduce the cast/NoSuchMethodError), now extending DeltaV2TestBase again.

File: build.sbt (hunk 1 above)
Comment (SanJSp) [reply build.sbt]: Done!

**Comment by SanJSp** [comment]
Changelog tests run and pass in private repo CI:
https://github.com/SanJSp/delta/actions/runs/26287328831/job/77378150469?pr=2

```

[warn] multiple main classes detected: run 'show discoveredMainClasses' to see the list
[info] Test run started (JUnit Jupiter)
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testTimestampRangeReadsAllChanges() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testChangelogRejectsTableWithoutRowTracking() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testTimestampRangeMixedBoundsStartExclusiveEndInclusive() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testSqlAndDataFrameChangesMatchForVersionRange() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testChangelogRejectsRowTrackingDisabledMidRange() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testTimestampRangePartialMiddleCommit() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testChangelogRejectsRowTrackingDisabledAtEnd() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testTimestampRangeRejectsEmptyExclusiveRange() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testTimestampRangeBeforeEarliestCommitFails() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testTimestampRangeAfterLatestCommitFails() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testChangelogRejectsSchemaChangeMidRange() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testUnboundedBatchChangesIsRejectedForNow() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testTimestampRangeOpenEndedReadsToLatest() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testTimestampRangeExclusiveBoundsSkipBoundaryCommits() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testTimestampRangeBetweenCommitTimestamps() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testTimestampRangeOpenEndedExclusiveStart() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogCatalogIntegrationTest#testTimestampRangeMixedBoundsStartInclusiveEndExclusive() started
[info] Test run finished: 0 failed, 0 ignored, 17 total, 56.929s
[info] Test run started (JUnit Jupiter)
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogDirectBatchExecutionTest#testDirectBatchExecutionWithExplicitExpectedRows() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogDirectBatchExecutionTest#testRowTrackingMetadataReferences() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogDirectBatchExecutionTest#testRangeSlicingNonZeroStart() started
[info] Test io.delta.spark.internal.v2.read.changelog.DeltaChangelogDirectBatchExecutionTest#testUpdateProducesPairedDeleteAndInsert() started
[info] Test run finished: 0 failed, 0 ignored, 4 total, 7.77s
[info] Passed: Total 21, Failed 0, Errors 0, Passed 21
[success] Total time: 368 s (06:08), completed May 22, 2026, 12:28:52 PM


```

File: spark/v2/src/main/java-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogBatch.java [hunk 3]
```diff
@@ -155,15 +155,19 @@ public InputPartition[] planInputPartitions() {
         } catch (RuntimeException e) {
           throw e;
         } catch (Exception e) {
-          throw new RuntimeException("Failed to process CDC commit actions", e);
+          // Include the inner message so AnalysisException error classes
+          // (e.g. DELTA_CHANGELOG_ROW_TRACKING_DISABLED_IN_RANGE) reach the user.
+          throw new RuntimeException(
```
Comment (johanl-db) [inline spark/v2/src/main/java-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogBatch.java:172]: (can be done as follow-up): It would be better to surface proper spark exceptions, with an error class, rather than generic runtime errors

File: build.sbt [hunk 4]
```diff
@@ -529,11 +529,21 @@ lazy val sparkV2 = {
...
   .disablePlugins(JavaFormatterPlugin, ScalafmtPlugin)
   .settings (
     name := "delta-spark",
+    // Exclude the released `delta-spark` jar that sparkV2's test deps
+    // (kernelUnityCatalog test->test -> kernelDefaults test->test ->
+    // "io.delta" %% "delta-spark" % "4.0.0" % "test") pull in transitively.
+    // The released jar contains a pre-#5320 DeltaCatalog.class that shadows
+    // the in-tree unified DeltaCatalog at the same FQN and produces
+    // ClassCastException / NoSuchMethodError on Spark 4.2.
+    // Scoped to Test so MiMa's compile-time previous-ABI lookup still resolves.
```
Comment (johanl-db) [inline build.sbt]: nit: remove, that's too much information
```suggestion
```

**Review by johanl-db — COMMENTED** [review]
Looks good to me, can you have @murali-db take a look also since he's working on the 4.2 build?

File: build.sbt (hunk 4 above)
Comment (SanJSp) [reply build.sbt]: Done

File: spark/v2/src/main/java-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogBatch.java (hunk 3 above)
Comment (SanJSp) [reply spark/v2/src/main/java-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogBatch.java:172]: Added to the backlog

**Review by murali-db — APPROVED** [review]

File: build.sbt [hunk 5]
```diff
@@ -529,11 +529,17 @@ lazy val sparkV2 = {
...
   .dependsOn(sparkV1)
-  .dependsOn(sparkV2)
+  // test->test so spark-unified test sources can reuse helpers like
+  // DeltaV2TestBase from sparkV2's test scope.
+  .dependsOn(sparkV2 % "compile->compile;test->test")
   .dependsOn(storage)
   .disablePlugins(JavaFormatterPlugin, ScalafmtPlugin)
   .settings (
     name := "delta-spark",
+    // Exclude the released `delta-spark` jar that sparkV2's test deps
```
Comment (tdas) [inline build.sbt]: i didnt get what is doing? released, non-test delta-spark jar will not have test dependencies. are you talking about the delta-spark tests jar? do we release that?

Comment (SanJSp) [reply build.sbt]: Hi TD, thanks for taking a look. 
I want to admit that build changes are a completly unknown terretory for me, hence those are very LLM supported changes.
When building with Spark 4.2 I kept receiving a `ClassCastException` at `AbstractDeltaCatalog.scala:1118`. This was due to an older released delta-spark jar which was added to the test classpath via transitive test dependencies and conflicting with the in-tree DeltaCatalog. To fix this I moved the tests to spark-unified and AFAIU there was then a race condition between the older and newer version of DeltaCatalog.class which this addition then decides. Thats how I understand it.

The issue seems to be in this line:

```
  // test->test so spark-unified test sources can reuse helpers like
  // DeltaV2TestBase from sparkV2's test scope.
  .dependsOn(sparkV2 % "compile->compile;test->test")
```

It adds a dependency from spark-unified / test  on sparkV2 / test . Then it goes down the chain of test dependencies as noted by the comment below (e.g. sparkV2 / test -> kernelUnityCatalog / test [here](http://github.com/SanJSp/delta/blob/71e886d65b2762fb2edf20682643115c4212c56f/build.sbt#L464)) which ends up pulling an [old version of delta-spark for testing that conflicts](https://github.com/SanJSp/delta/blob/71e886d65b2762fb2edf20682643115c4212c56f/build.sbt#L1166).

Seing the test->test dependency chain, don't you think this is a reasonable solution? Alternatively I could remove the dependency and instead duplicate around ~160 lines of helpers that I reuse in my tests. That could be a clear separation, but introduces code duplication. Not really pretty. 

<details>
<summary>LLM response for maybe more correctness</summary>
> You're right that the released delta-spark binary itself doesn't carry test deps -- the conflict is transitive. sparkV2's `test->test` chain reaches kernelDefaults/test, which declares `delta-spark % 4.0.0 % test` (build.sbt:1166) for its own catalog tests. Once spark-unified inherits sparkV2's test classpath, that 4.0.0 jar lands on it and its pre-#5320 `DeltaCatalog.class` (no `ChangelogSupport` mixin) wins classloader resolution against the in-tree class -- V2 changelog reads then fall back to the legacy `CDCReader`. The Test-scoped exclusion forces the in-tree class to win; MiMa's previous-ABI lookup still resolves the released jar in Compile/runtime contexts. The alternative is to drop `dependsOn(sparkV2 % "test->test")` and duplicate ~160 lines of DeltaV2TestBase into spark-unified -- removes the chain at the cost of duplicated test infrastructure.
</details>

Comment (tdas) [reply build.sbt]: okay.. lets debug. what happens if you remove these lines now?

Comment (tdas) [reply build.sbt]: specifically test exclusion lines.

Comment (SanJSp) [reply build.sbt]: I encountered issues whilst removing the dependencies, as 2 tests started to fail with assertion failures. Moving the tests to the original sparkV2 test path lead to the ClassCastException mentioned above. Due to time constraints, I opted to continue with removing this part and introducing the helpers in spark-unified. With this the tests pass again.

**Review by johanl-db — APPROVED** [review]

File: build.sbt [hunk 6]
```diff
@@ -561,6 +561,16 @@ lazy val spark = (project in file("spark-unified"))
 
     CrossSparkVersions.sparkDependentSettings(sparkVersion),
 
+    // Add version-specific test shim directory, e.g. `src/test/scala-shims/spark-4.2`.
```
Comment (tdas) [inline build.sbt]: can you please merge this section with the existing `Test / unmanagedSourceDirectories ` section 10 lines above

Comment (SanJSp) [reply build.sbt]: Done 😊

**Review by tdas — APPROVED** [review]
