### PR TITLE
[Spark] DV (Deletion Vector) support for the V2 changelog read path

### PR DESCRIPTION
**Pull request by SanJSp**
> **Stacked on #6830**. The diff below currently includes #6830's two commits at the base of the stack; once #6830 merges, the diff will shrink to this PR's three commits only. Reviewer focus is on the three top commits:
>
> ```
> 5924f4ba4  Fix tests after rebase
> 31b417d6b  Support DVs
> bfdeccc24  Setup TDD and function stubs
> ```
>
> The remaining failure modes covered by #6830 (classpath shadowing of `DeltaCatalog`, `ClassCastException` from `SupportsPathIdentifier`, `NoSuchMethodError` from `CatalogStorageFormat.copy`) are out of scope here.

#### Which Delta project/connector is this regarding?

- [x] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

## Description

Follow-up to #6794. Adds Deletion Vector (DV) support to the V2 changelog read path so `CHANGES FROM VERSION x TO VERSION y` returns correct results on tables with `delta.enableDeletionVectors=true`.

### Implementation

`DeltaChangelogBatch.java` (this PR's `Support DVs` commit):

- `CDCInputPartition` carries a per-file `deletionVectorInfo: String` (the base64-serialised DV descriptor, or `null` when the file has no DV).
- `planInputPartitions` extracts the DV per `AddFile` via `DeletionVectorDescriptor::serializeToBase64` and threads it onto the partition.
- `createReader` sets `DeltaParquetFileFormat.FILE_ROW_INDEX_FILTER_ID_ENCODED` and `FILE_ROW_INDEX_FILTER_TYPE` (with `RowIndexFilterType.IF_CONTAINED`) together on the per-file metadata, so the existing `DropMarkedRowsFilter` machinery picks up the DV and produces the correct `delete` change rows.

`PartitionUtils.java`:

- Small helper bump to expose the per-file metadata map used above.

### Tests (this PR's `Setup TDD` commit)

`DeltaChangelogDirectBatchExecutionTest.java`:

- Parameterized `testDirectBatchExecutionWithExplicitExpectedRows` and `testUpdateProducesPairedDeleteAndInsert` via `@ParameterizedTest @ValueSource(booleans = {false, true})` so each test runs once with DVs off (rewrite-on-delete) and once with DVs on (DV-on-delete). The expected row sets are identical, so the same assertions cover both physical layouts.

`DeltaChangelogDvTest.java` (new):

DV-specific scenarios that don't fit the parameterized variants.

- `test_mixedDvDelete_perFileBranching`: two AddFiles in one commit, one DELETE touching both, asserts that the per-file DV branch in `planInputPartitions` sets the DV constants independently per file.
- `test_multiVersionDvDeletes_perCommitIsolation`: two consecutive DV-DELETE commits, asserts that Catalyst's batch CDC post-processing partitions on `(row_id, version)` so each commit's carry-overs collapse independently.

### Test fixture: STRICT-mode scoping (this PR's `Fix tests after rebase` commit)

`DeltaChangelogDvTest`'s `withDvTable` originally ran the test body (CREATE TABLE, INSERTs, DELETEs, CHANGES read) under `spark.databricks.delta.v2.enableMode=STRICT`. That routes writes through the V2 connector, which does not populate `numRecords` statistics — Kernel then refuses the write with `KernelException: Cannot write to a rowTracking-supported table without 'numRecords' statistics`. Refactored the fixture to match the convention used by `DeltaChangelogCatalogIntegrationTest`:

- INSERTs / DELETEs run in the session-default `v2.enableMode=AUTO` (the V1 write path that populates `numRecords`).
- A new `withStrictV2` helper wraps only the CHANGES read, so `TableCatalog.loadChangelog` still routes through the V2 path.

### Correctness model

Same as #6794: Catalyst's batch CDC post-processor uses `_metadata.row_id` and `_metadata.row_commit_version` for Phase 1 carry-over removal and Phase 2 net-changes ranking. With DV enabled, deletes no longer rewrite the file; the changelog scan emits a synthetic delete row for each DV-marked row in the touched file at the commit's version. The row tracking metadata flows through unchanged.

## How was this patch tested?

Locally against Spark 4.2-preview4 (same setup as #6830 — see its "Quick reference" section for the cherry-pick + preview pin):

```
build/sbt -DsparkVersion=master \
  "set every scalastyleFailOnError := false" \
  "spark/testOnly io.delta.spark.internal.v2.read.changelog.*"
```

```
[info] Passed: Total 25, Failed 0, Errors 0, Passed 25
[success] Total time: 86 s
```

25 = 21 (existing CatalogIntegrationTest cases) + 2 (parameterized DV-on/off in DirectBatchExecutionTest) + 2 (new DvTest cases).

## Does this PR introduce _any_ user-facing changes?

The V2 changelog path remains internal (gated by `spark.databricks.delta.changelogV2.enabled`). When enabled, it now returns correct results on DV-enabled tables instead of missing or incorrectly emitting deleted rows.

### CODE REVIEW

File: spark/v2/src/main/java-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogBatch.java [hunk 1]
```diff
@@ -338,11 +355,23 @@ public PartitionReader<InternalRow> createReader(InputPartition partition) {
...
 
-      // TODO Sandro: when cdcPartition has DV info, add BOTH constants together to constantMetadata
-      // (touch-point 3): FILE_ROW_INDEX_FILTER_ID_ENCODED -> base64 string, and
-      // FILE_ROW_INDEX_FILTER_TYPE -> RowIndexFilterType.IF_CONTAINED.
-      // Hard pre-condition: never set just one of the two (DeltaParquetFileFormat throws).
-      // Consider reusing PartitionUtils.buildDvMetadata (touch-point 4) instead of inlining here.
+      // When the action carries a DV, set both Parquet reader constants together. Setting only
+      // one triggers IllegalStateException in DeltaParquetFileFormat. IF_CONTAINED makes the
+      // reader drop physical rows whose index is in the DV bitmap (visible-rows semantics).
+      // Could be replaced by a call to PartitionUtils.buildDvMetadata if its visibility is
```
Comment (johanl-db) [inline spark/v2/src/main/java-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogBatch.java]: >      // Could be replaced by a call to PartitionUtils.buildDvMetadata if its visibility is

Sounds like that's worth doing

File: spark-unified/src/test/scala-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogDvTest.java [hunk 2]
```diff
@@ -38,9 +38,10 @@ public class DeltaChangelogDvTest extends DeltaChangelogTestBase {
   // ===========================================================================================
 
   /**
-   * Create a DV-enabled, row-tracking-enabled table, then run the body under
-   * {@code spark.databricks.delta.v2.enableMode=STRICT} so CHANGES reads route through the V2
-   * path.
+   * Create a DV-enabled, row-tracking-enabled table. Writes (INSERT, DELETE) inside the body run
+   * under the session-default v2 mode (AUTO -&gt; V1 connector) so they go through the V1 write
```
Comment (johanl-db) [inline spark-unified/src/test/scala-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogDvTest.java]: nit: fix `AUTO -&gt; V1 connector`.

Also a bit confusing to set v2 mode to AUTO to go through V1 write path.
It's only the case right now because writing DVs (and prob. also row tracking) isn't supported in V2.. Maybe just don't say anything

**Review by johanl-db — COMMENTED** [review]
Reviewed the DV specific comits: 2442f02ad0ddd79ab6062fd0c18d37d6877143e8..954439b9877547dee0a003a9097afaeec348977a

not approving yet to avoid this PR getting merged while it's still stacked, but it's otherwise good to go

File: spark/v2/src/main/java-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogBatch.java (hunk 1 above)
Comment (SanJSp) [reply spark/v2/src/main/java-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogBatch.java]: Done. Made buildDvMetadata public, takes the base64 string directly (matches what CDCInputPartition carries)

File: spark-unified/src/test/scala-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogDvTest.java (hunk 2 above)
Comment (SanJSp) [reply spark-unified/src/test/scala-shims/spark-4.2/io/delta/spark/internal/v2/read/changelog/DeltaChangelogDvTest.java]: Done

**Comment by SanJSp** [comment]
Closing, as #6886 is merged
